# Interactive graph
This graph will visualize the three primary variables we have been studying: valence, danceability, and energy. Each song of each artist is plotted on the graph in their respective colors:

Taylor Swift: Blue

Fleetwood Mac: Orange

Doja Cat: Pink

Peso Pluma: Yellow

To interact with the D3 graph, hover over each circle to reveal detailed information about a specific track. The size of the circles corresponds to the energy level of the tracks, with larger circles indicating higher energy. The x-axis represents danceability, while the y-axis represents valence. Explore the graph to discover patterns and trends in how these musical features vary across tracks from different artists. The association of the artists to their respective color makes it easier to identify their contributions to the overall visualization. Additionally, the title "Spotify Analysis: Danceability vs. Valence" provides context for the graph's purpose. Use the axis labels to understand the scale and meaning of the plotted data. Enjoy exploring the Spotify analysis visualization!
<style>
  * {
    font-family: sans-serif;
  }
</style> 

<div id="plot">
</div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
<script src="scripts/myscript.js"></script>

